[package]
name = "mysearch"
version = "0.1.0"
authors = ["Taisuke Miyazaki <imishinist@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.125"
stable_deref_trait = "1.2.0"
tantivy = "0.14.0"
